name: Setup dependencies

runs:
  using: "composite"
  steps:
    - name: "Install deps"
      run: |        
          apt install -y curl xz
          curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh -s -- --daemon

