[package]
name = "dataloom-db-sqlite"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
license-file = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
dataloom-db-core = { workspace = true }
roxygen = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
either = { workspace = true }
itertools = { workspace = true }
r2d2_sqlite = "0.34.0"
r2d2 = "0.8.10"
rusqlite = "0.39.0"
