[workspace]
resolver = "3"
members = ["crates/*", "examples/*"]
default-members = ["crates/dataloom"]

[workspace.dependencies]
dataloom = { path = "crates/dataloom", version = "0.3.4"}
dataloom-macro = { path = "crates/dataloom-macro", version = "0.3.4" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[workspace.package]
version = "0.3.4"
edition = "2024"
description = "A database abstraction layer"
license-file = "LICENSE"
repository = "https://git.ole.blue/DestinyofYeet/dataloom"
readme = "README.md"
keywords = ["database", "abstraction", "task-scheduling", "tasks"]
categories = ["database"]
