[package]
name = "dataloom-macro"
version = "0.2.0"
edition = "2024"
repository = "https://git.ole.blue/DestinyofYeet/dataloom"
description = "Procmacro for dataloom"
license-file = "../LICENSE"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full"] }
