---
enable-email-notifications: true
name: "Upload to crates.io"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN  }}

jobs:
  publish_macro:
    runs-on: native
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Publish macro"
        working-directory: "./dataloom-macro"
        run: |
          nix run nixpkgs#cargo -- publish

  publish:
    runs-on: native
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Publish code"
        shell: nix shell nixpkgs#gcc nixpkgs#cargo --command sh -c {0}
        run: |
          cargo publish
