---
enable-email-notifications: false
name: "Upload to crates.io"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN  }}

# defaults:
#   run:
#     shell:
#       nix develop --command bash {0}

jobs:
  publish_macro:
    runs-on: ubuntu

    steps:
      - name: "Install deps"
        run: |
          apt update
          apt install -y git cargo

      - name: "Get src"
        run: |
          git clone https://git.ole.blue/${{ github.repository_owner }}/${{ github.repository }} --revision ${{ github.sha }} --depth 0 source
          cd source/dataloom-macro

      - name: "Check tag"
        run: |
          cargo install toml-cli
          test "v$(toml get Cargo.toml package.version)" = "${{ github.ref_name }}"

      - name: "Publish macro"
        run: |
          cargo publish

  publish:
    runs-on: ubuntu
    steps:
      - name: "Install deps"
        run: |
          apt update
          apt install -y git cargo

      - name: "Get src"
        run: |
          git clone https://git.ole.blue/${{ github.repository_owner }}/${{ github.repository }} --revision ${{ github.sha }} --depth 0 source
          cd source/dataloom-macro

      - name: "Check tag"
        run: |
          cargo install toml-cli
          test "v$(toml get Cargo.toml package.version)" = "${{ github.ref_name }}"

      - name: "Publish code"
        run: |
          cargo publish
