name: "Publish on crates.io"
inputs:
  working-directory:
    description: "The working directory to work in"

runs:
  using: "composite"
  steps:
    - name: "Publish macro"
      working-directory: ${{ inputs.working-directory }}
      shell: "nix develop --command bash {0}"
      run: |
        cargo publish
  
